### ISSUE TITLE
comments on initial release

### ISSUE THREAD

**Issue by zvkemp** [lumoslabs/i18n-instrument#1]
assignment expression inside ternary branch:
- https://github.com/lumoslabs/i18n-instrument/blob/master/lib/i18n/instrument/configurator.rb#L23
- https://github.com/lumoslabs/i18n-instrument/blob/master/lib/i18n/instrument/configurator.rb#L27
- etc

would suggest:

``` ruby
def on_lookup(&block)
  @on_lookup_proc ||= block
end
```

**Comment by zvkemp** [comment]
In general I find these exploded views difficult to grok:

https://github.com/lumoslabs/i18n-instrument/blob/master/lib/i18n/instrument/middleware.rb#L18

either keep the data on one line or keep each sub-structure on its own line

``` ruby
JS_RESPONSE = [
  200, 
  { 'Content-Type' => 'application/json', 'Content-Length' => 2 }, 
  ['{}']
]
```

**Comment by zvkemp** [comment]
Few minor comments, overall super cool!

**Comment by camertron** [comment]
Thanks @zach. I removed the ternary assignment expressions, I think this is good to go.
